#!/bin/sh
## DFE cron tasks

/usr/bin/php /var/www/console/artisan -q dfe:daily >>/var/www/console/storage/logs/crontab.log 2>&1
/usr/bin/php /var/www/console/artisan -q dfe:metrics --gather --force >>/var/www/console/storage/logs/crontab.log 2>&1
